#!/usr/bin/env python3
"""Generate a table-driven Verilator testbench for an arbitrary design.

Real-bug tier (bench/real): each benchmark ships a golden design, a buggy
variant and one or more CSV tables (RTL-Repair `TraceTestbench` format:
header = port names, one row per rising clock edge, inputs and outputs
mixed).  The rows were recorded by the original Verilog testbenches with
`@(posedge clk) $fwrite(...)`, i.e. every row is the value of all ports AT a
rising edge, before that edge's register updates.  The generated TB
therefore, for row k: drives the input columns, settles combinational logic
with the clock low, compares the output columns, then pulses the clock.
That is exactly the BTOR2 step semantics RTL-Repair's synthesizer assumes,
and because the stimulus is a fixed table the mutant can never perturb it —
open-loop replay (D1) is automatic for this tier.

Port names, directions and widths come from the Verilator-generated header
(VL_IN*/VL_OUT* declarations), so one generator serves every design.  The
CSV is read at RUN time; the same binary serves every table of a design.

    gen_table_tb.py --top axis_fifo --header obj/Vaxis_fifo.h -o tb_table.cpp

Runtime plusargs of the generated binary:
    +table=FILE   CSV table to drive/check (required)
    +trace=FILE   dump an all-signal VCD (used by the label pipeline/probe.sh)
    +clock=NAME   override clock-port detection
Protocol (house style): prints `PASS: rows=N` (rc 0) or
`FAIL @<row>: <port> got <v> expected <v>` at the first mismatch (rc 1).
Cells `x`/`X`/blank are don't-care.  Values are decimal, or hex with 0x.
"""
import argparse
import pathlib
import re
import sys

PORT_RE = re.compile(
    r"VL_(IN|OUT)(8|16|32|64|W)?\s*\(\s*&?\s*(\w+)\s*,\s*(\d+)\s*,\s*(\d+)"
    r"(?:\s*,\s*(\d+))?\s*\)")

TEMPLATE = r'''// GENERATED by scripts/gen_table_tb.py — do not edit.  Table-driven
// testbench for `$top` (see the generator's docstring for the row semantics).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <functional>
#include <sstream>
#include <string>
#include <vector>

#include "V$top.h"
#include "verilated.h"
#include "verilated_vcd_c.h"

struct Port {
  const char* name; bool is_in; int width;
  std::function<void(V$top*, uint64_t)> set;
  std::function<uint64_t(V$top*)> get;
};

static uint64_t mask(int w) { return w >= 64 ? ~0ull : ((1ull << w) - 1ull); }
static const bool SAMPLE_POST = $sample_post;  // generator --sample {pre,post}

static const std::vector<Port> PORTS = {
$ports
};

static std::string trim(std::string s) {
  size_t a = s.find_first_not_of(" \t\r\n"), b = s.find_last_not_of(" \t\r\n");
  return a == std::string::npos ? "" : s.substr(a, b - a + 1);
}

static std::vector<std::string> split(const std::string& line) {
  std::vector<std::string> out; std::string cell; std::stringstream ss(line);
  while (std::getline(ss, cell, ',')) out.push_back(trim(cell));
  return out;
}

static bool ieq(const std::string& a, const char* b) {
  if (a.size() != strlen(b)) return false;
  for (size_t i = 0; i < a.size(); i++) if (tolower(a[i]) != tolower(b[i])) return false;
  return true;
}

int main(int argc, char** argv) {
  Verilated::commandArgs(argc, argv);
  Verilated::traceEverOn(true);
  auto arg = [](const char* name) -> std::string {
    const char* v = Verilated::commandArgsPlusMatch(name);
    const char* eq = (v && *v) ? strchr(v, '=') : nullptr;
    return eq ? std::string(eq + 1) : std::string();
  };
  std::string table = arg("table"), trace = arg("trace"), clock_override = arg("clock");
  if (table.empty()) { fprintf(stderr, "usage: sim +table=FILE [+trace=FILE] [+clock=NAME]\n"); return 2; }
  std::ifstream in(table);
  if (!in) { fprintf(stderr, "FAIL: cannot open table %s\n", table.c_str()); return 2; }

  // Header -> column binding.  Every column must name a port; every input
  // port not in the table is a clock candidate (or is held at 0).
  std::string line;
  if (!std::getline(in, line)) { fprintf(stderr, "FAIL: empty table\n"); return 2; }
  std::vector<std::string> header = split(line);
  std::vector<const Port*> cols;
  for (auto& h : header) {
    if (h.empty()) { cols.push_back(nullptr); continue; }  // trailing comma
    if (ieq(h, "time") || ieq(h, "cycle") || ieq(h, "step")) { cols.push_back(nullptr); continue; }  // meta column (CirFix tables)
    const Port* found = nullptr;
    for (auto& p : PORTS) if (h == p.name) { found = &p; break; }
    if (!found) for (auto& p : PORTS) if (ieq(h, p.name)) { found = &p; break; }
    if (!found) { fprintf(stderr, "FAIL: table column '%s' is not a port of $top\n", h.c_str()); return 2; }
    cols.push_back(found);
  }
  const Port* clk = nullptr;
  std::vector<const Port*> unbound_inputs;
  for (auto& p : PORTS) {
    if (!p.is_in) continue;
    bool bound = false;
    for (auto c : cols) if (c == &p) bound = true;
    if (bound) continue;
    if (!clock_override.empty() ? (clock_override == p.name) : (strcasestr(p.name, "clk") || strcasestr(p.name, "clock"))) {
      if (clk) { fprintf(stderr, "FAIL: multiple clock candidates (%s, %s); use +clock=NAME\n", clk->name, p.name); return 2; }
      clk = &p;
    } else {
      unbound_inputs.push_back(&p);
    }
  }
  // Three clocking modes, all preserving "outputs are checked BEFORE this
  // row's clock edge":
  //   pulse   : clock is a port absent from the table -> we pulse it after
  //             the compare (fpga-debugging tables, one row per edge)
  //   table   : the table itself carries the clock column (CirFix tables
  //             sampled by time) -> apply it AFTER the compare, so a row
  //             with clk=1 is compared pre-edge exactly like the recorder's
  //             `@(posedge clk) $fwrite`
  //   none    : no clock at all (combinational design) -> no edge
  const Port* table_clk = nullptr;
  for (auto c : cols)
    if (c && c->is_in && (!clock_override.empty() ? (clock_override == c->name)
                          : (strcasestr(c->name, "clk") || strcasestr(c->name, "clock"))))
      table_clk = c;
  if (!clk && !table_clk && !unbound_inputs.empty()) {
    fprintf(stderr, "FAIL: no clock port found and %zu input(s) absent from the table\n", unbound_inputs.size());
    return 2;
  }
  for (auto p : unbound_inputs) fprintf(stderr, "note: input %s not in table; held at 0\n", p->name);

  V$top* dut = new V$top;
  VerilatedVcdC* vcd = nullptr;
  if (!trace.empty()) { vcd = new VerilatedVcdC; dut->trace(vcd, 99); vcd->open(trace.c_str()); }
  for (auto p : unbound_inputs) p->set(dut, 0);
  if (clk) clk->set(dut, 0);

  uint64_t row = 0, t = 0;
  int rc = 0;
  while (std::getline(in, line)) {
    if (trim(line).empty()) continue;
    std::vector<std::string> cells = split(line);
    // 1. drive inputs for this edge (the table's clock column, if any, is
    //    applied after the compare in step 3)
    for (size_t i = 0; i < cols.size() && i < cells.size(); i++) {
      const Port* p = cols[i];
      if (!p || !p->is_in || p == table_clk || cells[i].empty() || ieq(cells[i], "x")) continue;
      p->set(dut, strtoull(cells[i].c_str(), nullptr, cells[i].rfind("0x", 0) == 0 ? 16 : 10) & mask(p->width));
    }
    dut->eval();
    // Edge placement.  PRE (default, docs D6): compare, then edge — the
    // recorder's `@(posedge clk) $fwrite` saw pre-NBA values.  POST (some
    // CirFix recorders sampled after the update): edge, then compare.
    auto edge = [&]() {
      if (clk) {
        clk->set(dut, 1); dut->eval();
        clk->set(dut, 0); dut->eval();
      } else if (table_clk) {
        // A clock column recorded by `@(posedge clk) $fwrite` reads 1 on
        // every row (CirFix tables): each such row IS an edge.  Pulse on rows
        // whose clock cell is 1; a 0 cell means no edge at this sample.
        for (size_t i = 0; i < cols.size() && i < cells.size(); i++)
          if (cols[i] == table_clk && !cells[i].empty() && !ieq(cells[i], "x")
              && (strtoull(cells[i].c_str(), nullptr, 10) & 1)) {
            table_clk->set(dut, 1); dut->eval();
            table_clk->set(dut, 0); dut->eval();
          }
      }
    };
    if (SAMPLE_POST) edge();
    if (vcd) vcd->dump(t);
    // 2. check outputs
    for (size_t i = 0; i < cols.size() && i < cells.size(); i++) {
      const Port* p = cols[i];
      if (!p || p->is_in || cells[i].empty() || ieq(cells[i], "x")) continue;
      uint64_t exp = strtoull(cells[i].c_str(), nullptr, cells[i].rfind("0x", 0) == 0 ? 16 : 10) & mask(p->width);
      uint64_t got = p->get(dut) & mask(p->width);
      if (got != exp) {
        printf("FAIL @%llu: %s got %llu expected %llu\n", (unsigned long long)row, p->name,
               (unsigned long long)got, (unsigned long long)exp);
        rc = 1;
        break;
      }
    }
    if (rc) break;
    // 3. (PRE mode) the edge for this row.  The VCD is dumped once per row
    // at the moment the row's outputs were checked, so VCD tick k == table
    // row k in both modes.
    if (!SAMPLE_POST) edge();
    t += 1; row++;   // VCD time unit == table row (vcd_query reports time as the cycle)
  }
  if (!rc) printf("PASS: rows=%llu\n", (unsigned long long)row);
  if (vcd) { vcd->dump(t + 1); vcd->close(); delete vcd; }
  dut->final(); delete dut;
  return rc;
}
'''


def parse_ports(header_text: str):
    ports = []
    for m in PORT_RE.finditer(header_text):
        direction, kind, name, msb, lsb, words = m.groups()
        ports.append({"name": name, "is_in": direction == "IN",
                      "width": int(msb) - int(lsb) + 1, "wide": kind == "W"})
    return ports


def port_entry(top: str, p: dict) -> str:
    if p["wide"]:
        # >64-bit ports: bind word 0 only; the table format is 64-bit decimal.
        setter = f"[](V{top}* d, uint64_t v) {{ d->{p['name']}[0] = (uint32_t)v; d->{p['name']}[1] = (uint32_t)(v >> 32); }}"
        getter = f"[](V{top}* d) -> uint64_t {{ return ((uint64_t)d->{p['name']}[1] << 32) | d->{p['name']}[0]; }}"
    else:
        setter = f"[](V{top}* d, uint64_t v) {{ d->{p['name']} = v; }}"
        getter = f"[](V{top}* d) -> uint64_t {{ return d->{p['name']}; }}"
    return (f'  {{"{p["name"]}", {"true" if p["is_in"] else "false"}, {p["width"]}, '
            f"{setter}, {getter}}},")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--top", required=True)
    ap.add_argument("--header", required=True, type=pathlib.Path,
                    help="Verilator-generated V<top>.h")
    ap.add_argument("-o", "--out", required=True, type=pathlib.Path)
    ap.add_argument("--sample", choices=("pre", "post"), default="pre",
                    help="compare outputs before (default, docs D6) or after "
                         "the row's clock edge; 'post' for recorders that "
                         "sampled after the update (CirFix reed_solomon)")
    a = ap.parse_args()
    ports = parse_ports(a.header.read_text())
    if not ports:
        print(f"no VL_IN/VL_OUT ports found in {a.header}", file=sys.stderr)
        return 1
    wide = [p["name"] for p in ports if p["wide"] and p["width"] > 64]
    if wide:
        print(f"note: >64-bit ports bound to their low 64 bits: {wide}", file=sys.stderr)
    body = "\n".join(port_entry(a.top, p) for p in ports)
    a.out.write_text(TEMPLATE.replace("$ports", body).replace("$top", a.top)
                     .replace("$sample_post", "true" if a.sample == "post" else "false"))
    print(f"wrote {a.out}: {sum(p['is_in'] for p in ports)} inputs, "
          f"{sum(not p['is_in'] for p in ports)} outputs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
